### ISSUE TITLE
都道府県検索機能を服装指数チェック機能に変更する

### ISSUE THREAD

**Issue by ryusei-tadokoro** [ryusei-tadokoro/today_fashion#89]
- [x] 服装チェック表の作成
- [x] ヘッダーの都道府県検索機能を他の場所に移動
- [x] 空いたところに、服装チェック機能を追加

**Comment by ryusei-tadokoro** [comment]
お疲れ様です。
服装指数チェック機能の変更に伴い、日本地図をmap.html.erbに表示させようとしたところ、
日本地図が表示されない状況なため、ご相談させてください。
以下いろんな方法で試しましたが、表示されませんでした。

https://github.com/ryusei-tadokoro/today_fashion/pull/133
https://github.com/ryusei-tadokoro/today_fashion/pull/135
https://github.com/ryusei-tadokoro/today_fashion/pull/134

参考にした記事
https://takemaru-hirai.github.io/japan-map/
https://qiita.com/Kurosuke_4/items/815c7aecbe78886a4843
https://ryucoding.com/programming/japan-map-js-covid

例えば
https://github.com/ryusei-tadokoro/today_fashion/pull/134 では以下の記事を参考に導入を試みました
https://ryucoding.com/programming/japan-map-js-covid

[![Image from Gyazo](https://i.gyazo.com/f610b14e4605eda214c0a9cabd2cfd93.png)](https://gyazo.com/f610b14e4605eda214c0a9cabd2cfd93)
このようなエラーが発生しており、japanMapが定義されていないことが原因とのことでしたが、

application.html.erb
```
<!DOCTYPE html>
<html>
  <head>
    <title>TodayFashion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= display_meta_tags(default_meta_tags) %>

    <!-- Bootstrap CSSをインクルード -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Bootstrap JSとPopper.jsをインクルード -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="d-flex flex-column vh-100">
      <% if user_signed_in? %>
        <%= render 'shared/header' %> 
        <div class="container flex-grow-1" style="padding-top: 90px;">
          <% flash.each do |type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{type == 'notice' ? 'success' : 'danger'}") %>
          <% end %>
        </div>
      <% end %>
      <main class="flex-grow-1 mb-auto">
        <%= yield %>
      </main>
      <% if user_signed_in? %>
        <%= render 'shared/footer' %>
      <% end %>
    </div>    
    <!-- Japan Mapのスクリプトを追加 -->
    <script src="https://cdn.jsdelivr.net/npm/japan-map@1.0.0/dist/japan-map.min.js"></script>
  </body>
</html>

```

map.js
```
document.addEventListener('DOMContentLoaded', () => {
  if (typeof japanMap !== 'undefined') {
    japanMap({
      element: '#map',
      width: 800,
      height: 600,
      onSelect: function(data) {
        alert('Selected prefecture: ' + data.name);
      }
    });
  } else {
    console.error('japanMap is not defined');
  }
});

```

application.js
```
import "core-js/stable";
import "regenerator-runtime/runtime";
import Rails from "@rails/ujs";
import $ from "jquery";
import "bootstrap";
import "./scripts"; // scripts.js
import "./closet_form"; // closet_form.js
import './map';

if (typeof Rails !== 'undefined') {
  Rails.start();
}

window.$ = $;
window.jQuery = $;

$(document).ready(function() {
  var flashNotice = document.querySelector(".alert");
  if (flashNotice) {
    alert(flashNotice.textContent.trim());
    flashNotice.remove(); // アラートが表示された後に要素を削除
  }
  if (document.URL.match(/new/)) {
    import(/* webpackChunkName: "vision_api" */ './vision_api').then(module => {
      const visionAPI = module.default;
      visionAPI();
    });
  }

  function previewImage(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $('#preview-image').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $(document).on('change', '#user_image, #image-upload', function() {
    previewImage(this);
  });

  // CSRFトークンをヘッダーに設定
  const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': token
    }
  });

  // ここでjQueryのオブジェクトに対して.eachを使用します。
  $('[data-refresh-csrf]').each(function() {
    var element = $(this);
  });

  // カスタム削除確認ダイアログ
  $('a[data-method="delete"]').each(function(index, element) {
    $(element).on('click', function(event) {
      event.preventDefault();
      if (confirm('本当によろしいですか？')) {
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = this.href;

        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = '_method';
        hiddenField.value = 'delete';

        form.appendChild(hiddenField);

        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        var csrfField = document.createElement('input');
        csrfField.type = 'hidden';
        csrfField.name = 'authenticity_token';
        csrfField.value = csrfToken;

        form.appendChild(csrfField);
        document.body.appendChild(form);
        form.submit();
      } else {
        return false;
      }
    });
  });
});

```

map.html.erb
```
<div id="map"></div>

```

お手数をおかけいたしますが、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
お疲れ様です。

https://github.com/takemaru-hirai/japan-map

パッと↑見た感じですが、jquery.japan-mao.jp（GitHub上にあるもの）を使う必要があるようですが、そのままちゃんと使用できているか確認してみましたか。

まずは公式ドキュメントにあるとおりにやってみて期待している結果が得られるか、得られたらRailsのレールにそれをどのようにすれば乗っかるか、段階を経ていくと良いかと思いました。

https://ryucoding.com/programming/japan-map-js-covid
↑はJapan Map（jQuery plugin）では無さそうなので参考にはならないかと！

**Comment by ryusei-tadokoro** [comment]
コメントありがとうございます。
返信が遅くなり申し訳ありません。
以下最新コードをpush
https://github.com/ryusei-tadokoro/today_fashion/pull/136

行った手順について説明いたします。
以下URLからzipファイルをダウンロード、jquery.japan-map.jsとjquery.japan-map.min.jsをapp/javascript配下に設置
https://takemaru-hirai.github.io/japan-map/

routeの更新
```
  get 'weather/map', to: 'weather#map'
```

コントローラーの更新（punditエラーが生じるためpolicy.rbも作成(GitHub Copilotにて生成）)
```
  def map
    city_name = params[:city_name]
    @weather_data = fetch_weather_data(city_name)
    if @weather_data
      authorize @weather_data, policy_class: WeatherDataPolicy
    else
      redirect_to action: :index, alert: '天気情報の取得に失敗しました。'
    end
  end
```

```
class WeatherPolicy < ApplicationPolicy
  def map?
  end
end
```

```
class WeatherDataPolicy
  attr_reader :user, :weather_data

  def initialize(user, weather_data)
    @user = user
    @weather_data = weather_data
  end

  def map?
    user.admin? || weather_data['name'] == '新宮市'
  end
end
```

app/views/weather/map.html.erb
```
<!DOCTYPE html>
<html>
<head>
    <title>Japan Map - EXAMPLE 1</title>
    <!-- jQueryのCDNを追加 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- 開発用または本番用のスクリプトタグを選択して使用 -->
    <!-- 開発中は非圧縮版を使用 -->
    <script src="./jquery.japan-map.js"></script>
    <!-- 本番環境では圧縮版を使用 -->
    <!-- <script src="./jquery.japan-map.min.js"></script> -->
    <script>
        $(function(){
            $("#map-container").japanMap({
                onSelect : function(data){
                    alert(data.name);
                }
            });
        });
    </script>
</head>
<body>
<div id="map-container"></div>
</body>
</html>
```

application.js
```
import "core-js/stable";
import "regenerator-runtime/runtime";
import Rails from "@rails/ujs";
import $ from "jquery";
import "bootstrap";
import "./scripts";
import "./closet_form";
import "./jquery.japan-map.js";

if (typeof Rails !== 'undefined') {
  Rails.start();
}

window.$ = $;
window.jQuery = $;

$(document).ready(function() {
  var flashNotice = document.querySelector(".alert");
  if (flashNotice) {
    alert(flashNotice.textContent.trim());
    flashNotice.remove(); // アラートが表示された後に要素を削除
  }
  if (document.URL.match(/new/)) {
    import('./vision_api').then(module => {
      const visionAPI = module.default;
      visionAPI();
    });
  }

  function previewImage(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $('#preview-image').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $(document).on('change', '#user_image, #image-upload', function() {
    previewImage(this);
  });

  // CSRFトークンをヘッダーに設定
  const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': token
    }
  });

  // ここでjQueryのオブジェクトに対して.eachを使用します。
  $('[data-refresh-csrf]').each(function() {
    var element = $(this);
  });

  // カスタム削除確認ダイアログ
  $('a[data-method="delete"]').each(function(index, element) {
    $(element).on('click', function(event) {
      event.preventDefault();
      if (confirm('本当によろしいですか？')) {
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = this.href;

        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = '_method';
        hiddenField.value = 'delete';

        form.appendChild(hiddenField);

        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        var csrfField = document.createElement('input');
        csrfField.type = 'hidden';
        csrfField.name = 'authenticity_token';
        csrfField.value = csrfToken;

        form.appendChild(csrfField);
        document.body.appendChild(form);
        form.submit();
      } else {
        return false;
      }
    });
  });
});
```

コンバイルエラーが生じるため以下のコードを実施
```
rails assets:clobber 

rails assets:precompile
```

現在のエラーです
```
http://localhost:3000/weather/map に移動しました
map:97 
        
        
       GET http://localhost:3000/weather/jquery.japan-map.js net::ERR_ABORTED 404 (Not Found)
jquery.min.js:2 jQuery.Deferred exception: $(...).japanMap is not a function TypeError: $(...).japanMap is not a function
    at HTMLDocument.<anonymous> (http://localhost:3000/weather/map:102:33)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30005)
    at t (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout（非同期）
（匿名） @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: $(...).japanMap is not a function
    at HTMLDocument.<anonymous> (map:102:33)
    at e (jquery.min.js:2:30005)
    at t (jquery.min.js:2:30307)
```

ファイル名やディレクトリ内にあるにもかかわらずこのエラーが発生しております。
エラー改善するにはどうすればよろしいでしょうか。
ご教授のほど、よろしくお願いいたします。

**Comment by ryusei-tadokoro** [comment]
先日より改善を試みました。

```
jQuery.fn.jquery 
'3.7.1'
```
バージョンによる違いが発生して表示されていないと思い訂正しました。
app/views/weather/map.html.erb
```
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
```

しかし、改善されませんでした。

エラーをなくすため、コードをいくつか変更しました

application.js
```
import "core-js/stable";
import "regenerator-runtime/runtime";
import Rails from "@rails/ujs";
import $ from "jquery";
import "bootstrap";
import "./scripts";
import "./closet_form";
import "./jquery.japan-map"; // Ensure jquery.japan-map is after jQuery import

if (typeof Rails !== 'undefined') {
  Rails.start();
}

window.$ = $;
window.jQuery = $;

$(document).ready(function() {
  var flashNotice = document.querySelector(".alert");
  if (flashNotice) {
    alert(flashNotice.textContent.trim());
    flashNotice.remove(); // Remove element after showing the alert
  }
  if (document.URL.match(/new/)) {
    import('./vision_api').then(module => {
      const visionAPI = module.default;
      visionAPI();
    });
  }

  function previewImage(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $('#preview-image').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $(document).on('change', '#user_image, #image-upload', function() {
    previewImage(this);
  });

  // Set CSRF token in headers
  const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': token
    }
  });

  $('a[data-method="delete"]').each(function(index, element) {
    $(element).on('click', function(event) {
      event.preventDefault();
      if (confirm('本当によろしいですか？')) {
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = this.href;

        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = '_method';
        hiddenField.value = 'delete';

        form.appendChild(hiddenField);

        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        var csrfField = document.createElement('input');
        csrfField.type = 'hidden';
        csrfField.name = 'authenticity_token';
        csrfField.value = csrfToken;

        form.appendChild(csrfField);
        document.body.appendChild(form);
        form.submit();
      } else {
        return false;
      }
    });
  });

  // Initialize JapanMap
  if (document.getElementById("map-container")) {
    $("#map-container").japanMap({
      onSelect: function(data) {
        alert(data.name);
      }
    });
  }
});

```

map.html.erb
```
<!DOCTYPE html>
<html>
<head>
    <title>Japan Map - EXAMPLE 1</title>
</head>
<body>
    <div id="map-container"></div>
</body>
</html>

```
現在のエラー
```
application.debug-261228f1ac75b355fca708fa110269371bbf8ab7edff76d1e3234752b707c1c7.js:30482 Uncaught ReferenceError: jQuery is not defined
```

このようになっています。
仮にviewファイルを空白にしても同じエラーが発生することからjavascriptのコードにエラーの原因があると思われます。
(ダウンロードしたファイルjquery.japan-map.jsの最後の行　})(jQuery);　にばつ印がついています）

**Comment by Tsuchiya2** [comment]
ちょっとコードを確認しましたが、いろいろ雑多になってしまっている印象を受けたため、直接該当のビューファイルに表示する例を共有しておきますね。以下参考に頑張ってみてください。

```
<!DOCTYPE html>
<html>
<head>
  <title>Japan Map Example</title>
  <script
    src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
    crossorigin="anonymous"></script>
  <style>
    /* 必要に応じてスタイルを追加 */
    #map-container {
      width: 100%;
      height: 600px; /* 適切な高さを指定 */
    }
  </style>
</head>
<body>

<div id="map-container"></div>

<script>
  ;(function($){
    "use strict";

    // Define the prefectures and map data below as per your requirements
    var definition_of_allJapan = {/* 全日本のデータをここに定義 */};
    var definition_of_prefectures = {/* 県データをここに定義 */};

    $.fn.japanMap = function(options){
        var target = $(this);

        for (var option in options)
            if (options.hasOwnProperty(option) && options[option] == null) options[option] = undefined;

        options = $.extend({
            type                : "canvas",
            selection           : "prefecture",
            width               : null,
            height              : null,
            color               : "#a0a0a0",
            hoverColor          : null,
            backgroundColor     : "transparent",
            borderLineColor     : "#ffffff",
            borderLineWidth     : 0.25,
            lineColor           : "#a0a0a0",
            lineWidth           : 1,
            drawsBoxLine        : true,
            showsPrefectureName : false,
            prefectureNameType  : "full",
            showsAreaName       : false,
            areaNameType        : "full",
            areas               : definition_of_allJapan,
            prefectures         : definition_of_prefectures,
            movesIslands        : false,
            font                : "Arial",
            fontSize            : null,
            fontColor           : null,
            fontShadowColor     : null,
            onSelect            : function(){},
            onHover             : function(){}
        }, options);

        var map;
        map = new MapCanvas(options);
        target.append(map.element);
        map.render();
        map.addEvent();

        return target;
    };

    // Base Class and other helper functions
    // (省略していますが、あなたが提供した元のコードをここに含めてください)

    // Add jQuery plugin initialization
    $(function(){
        $("#map-container").japanMap({
            onSelect : function(data){
                alert(data.name);
            }
        });
    });

  })(jQuery);
</script>

</body>
</html>
```

<img width="660" alt="image" src="https://github.com/user-attachments/assets/3f395bfe-118d-4d91-b007-47586fa86152">

**Comment by ryusei-tadokoro** [comment]
ありがとうございます。viewファイルを参考に一度実装に取り組んでみたいと思います。
